---
- name: Install, start, and enable httpd
  hosts: web_servers
  tasks:
    - name: Ensure httpd is installed
      package:
        name: httpd
        state: latest
      become: true

    - name: Ensure httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
      become: true
