---
- name: Configure Linux standard settings
  hosts: linux_servers
  gather_facts: false
  become: true
  tasks:
    - name: Import role
      ansible.builtin.import_role:
        name: linux_std_setting
