---
- name: Bootstrap playbook for virtual-machie
  hosts: localhost
  gather_facts: true

  vars:
    username: "{{ lookup('ansible.builtin.env', 'VBOX_USERNAME', default='ansible') }}"
    password: "{{ lookup('ansible.builtin.env', 'VBOX_PASSWORD', default='changeme') }}"

  tasks:
    - name: Create VBOX_USERNAME group
      ansible.builtin.group:
        name: "{{ username }}"
      become: true

    - name: Create VBOX_USERNAME user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | ansible.builtin.password_hash('sha512', inventory_hostname) }}"
        append: true
        groups:
          - "{{ username }}"
          - wheel
      become: true

    - name: Enable PasswordAuthentication in sshd_config
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication no$"
        state: absent
      become: true
      notify:
        - "Restart sshd service"

    - name: Copy /etc/hosts
      ansible.builtin.copy:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"

    - name: Copy ansible.cfg to $HOME
      ansible.builtin.copy:
        src: ansible.cfg
        dest: "{{ item.value }}/.ansible.cfg"
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: "0644"
      with_dict:
        - vagrant: /home/vagrant
        - ansible: /home/ansible

  handlers:
    - name: Restart sshd service
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: true
