---
- name: Adding multiple users based on distribution with error handling
  hosts: node01.example.com
  vars:
    usernames:
      - hiroshi
      - kento
      - lisa
      
  tasks:
    - block:
        - name: Ensure a user with a suffix '_fed' is added on Fedora
          user:
            name: "{{ item }}_fed"
            state: present
          loop: "{{ usernames }}"
          when: ansible_facts['distribution'] == "Fedora"
          become: true

      rescue:
        - name: Log failure
          debug:
            msg: "Failed to add user {{ item }}_fed on Fedora"

      always:
        - name: Check users
          command: cat /etc/passwd
          register: users_list
        - name: Show users
          debug:
            msg: "{{ users_list.stdout }}"
