---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awxbackup-pvc
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
