---
- name: Ensure custom motd file exists
  hosts: node00.example.com
  tasks:
    - name: Deploy motd template
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
      become: true
