---
- name: Success Case Playbook for DeprecatedVariableRule
  hosts: localhost
  tasks:
    - name: Display a message with recommended variable syntax
      debug:
        msg: "Hello, {{ username }}!"

    - name: Use a variable in a condition
      when: "{{ condition_var }} == true"
      debug:
        msg: "This condition uses the recommended syntax."
