---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.12.1
  - awx-app.yaml
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.12.1
namespace: awx
